# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

pod 'Alamofire', '~> 3.1.2'
pod 'SDWebImage', '~> 3.7.3'
pod 'SVProgressHUD', '~> 2.0-beta'
pod 'SnapKit', '~> 0.17.0'
pod 'FFLabel', '~> 0.0.2'
